version: 0.2

phases:
  build:
    commands:
      - echo "Pulling FilmDrop UI release ..."
      - export FILMDROP_UI_URL="${FILMDROP_UI_SOURCE_URL:-https://github.com/Element84/filmdrop-ui/archive/refs/tags/${FILMDROP_UI_TAG}.tar.gz}"
      - echo "Source URL - $FILMDROP_UI_URL"
      - wget --secure-protocol=TLSv1_2 -q -O filmdrop-ui.tgz "$FILMDROP_UI_URL"
      - export FILMDROP_UI_DIR="filmdrop-ui-${FILMDROP_UI_TAG#v}"
      - tar -xzf filmdrop-ui.tgz
      - cd "$FILMDROP_UI_DIR"
      - rm -f ./src/assets/config.*
      - echo "Setting environment variables for the Filmdrop UI ..."
      - echo $FILMDROP_UI_CONFIG | base64 --decode >> ./public/config/config.json
      - echo $FILMDROP_UI_LOGO | base64 --decode >> ./public/${FILMDROP_UI_LOGO_FILE##*/}
      - echo "Building FilmDrop UI release ..."
      - npm install
      - npm run build
      - cd build
      - echo "Pushing FilmDrop UI release to S3..."
      - echo $CONTENT_BUCKET
      - aws s3 sync --delete . s3://$CONTENT_BUCKET --acl bucket-owner-full-control
